version: '3.4'

networks:
    kafka-net:
      driver: bridge

services:  
  
    kafka:
        image: confluentinc/cp-kafka:7.6.1
        container_name: kafka
        ports:
          - "9092:9092"
        environment:
          # Node and roles
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller

          # Listeners
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
          KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"

          # Replication & transaction logs
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

        volumes:
          - kafka-data:/var/lib/kafka/data

        # Format storage automatically if missing
        entrypoint: >
          bash -c "
          if [ ! -f /var/lib/kafka/data/meta.properties ]; then
            echo 'Formatting Kafka storage with Cluster ID';
            CLUSTER_ID=$(kafka-storage random-uuid);
            kafka-storage format --ignore-formatted -t $CLUSTER_ID -d /var/lib/kafka/data;
          fi;
          /etc/confluent/docker/run"          

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui
        depends_on:
        - kafka
        ports:
        - "8080:8080"
        restart: always 
        environment:
         KAFKA_CLUSTERS_0_NAME: local
         KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
         KAFKA_CLUSTERS_0_ZEEKEEPER: ""
  
volumes:
  kafka-data:  
  