version: '3.4'

services:

  user-api:
    build:
     context: ./Services/User    
     dockerfile: User.API/Dockerfile
    container_name: user-api
    #networks:
    #   - kafka-net
    environment:
       ASPNETCORE_ENVIRONMENT: Development
       #Kafka__BootstrapServers: localhost:9092    
    ports:
      - "5001:8080"
    depends_on: 
      - kafka

  ordering-api:
    build: 
     context: ./Services/Ordering    
     dockerfile: Ordering.API/Dockerfile
    container_name: ordering-api
    #networks:
    #   - kafka-net
    environment:
       ASPNETCORE_ENVIRONMENT: Development
       #Kafka__BootstrapServers: localhost:9092    
    ports:
      - "5002:8080"     
    depends_on: 
      - kafka
  

 

